global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'localhost:9090'

  - job_name: 'dotnet-api'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'PostTechFiap.Api:8080'

  - job_name: 'node-exporter'
    static_configs:
      - targets: 
          - 'node-exporter:9100'
          