apiVersion: 1
datasources:
  - name: 'Prometheus'
    type: 'prometheus'
    url: http://prometheus:9090/
    access: proxy
    editable: true
    version: 1
    org_id: 1
    uid: "8rTXXfF4z"
    is_default: true
    jsonData:
      manageAlerts: true
      httpMethod: POST
