apiVersion: v1
kind: Service
metadata:
    name: posttechfiap-api-createcontactcommandconsumer-service
spec:
    selector:
        app: posttechfiap-createcontactcommandconsumer-api
    ports:
    - protocol: TCP
      port: 1001
      targetPort: 1001
    type: ClusterIP