apiVersion: apps/v1
kind: Deployment
metadata:
  name: posttechfiap-updatecontactcommandconsumer-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posttechfiap-updatecontactcommandconsumer-api
  template:
    metadata:
      labels:
        app: posttechfiap-updatecontactcommandconsumer-api
    spec:
      containers:
      - name: posttechfiap-updatecontactcommandconsumer-api
        image: onlyoutsider/posttechfiapapi-updatecontactcommandconsumer:latest
        ports:
        - containerPort: 1001