name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  Build_Tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20  # Increase timeout to 20 minutes
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore PosTechFiap.sln

    - name: Build
      run: dotnet build PosTechFiap.sln --no-restore

    - name: Ensure Docker is running
      run: |
        sudo systemctl start docker
        sudo systemctl status docker

    - name: List all Docker containers
      run: docker ps -a

    - name: Run tests
      run: dotnet test PosTechFiap.sln --no-build --verbosity normal

    - name: List all Docker containers after tests
      run: docker ps -a

    - name: Get logs of all Docker containers
      run: |
        for container in $(docker ps -a -q); do
          echo "Logs for container $container:"
          docker logs $container
        done
