name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  Build_Tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore PosTechFiap.sln

    - name: Build
      run: dotnet build PosTechFiap.sln --no-restore

    - name: Run tests
      env:
        Settings__DbConnectionString: "Server=localhost,1433;Database=Teste;User Id=SA;Password=YourStrong!Passw0rd;"
      run: dotnet test PosTechFiap.sln --no-build --verbosity normal
